### ISSUE TITLE
tokenPrice for ETH showing 0 when get account balance

### ISSUE THREAD

**Issue by aminhdev** [Ankr-network/ankr.js#11]
**I tried to use this example from the docs but got tokenPrice = 0 for ETH**
`curl --location --request POST 'https://rpc.ankr.com/multichain' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "ankr_getAccountBalance",
    "params": {
        "blockchain": "eth",
        "walletAddress": "0xfa9019df60d3c710d7d583b2d69e18d412257617"
    },
    "id": 1
}'`

**Current result for ETH tokenPrice**
```
[
...
{
      "blockchain": "eth",
      "tokenName": "Ethereum",
      "tokenSymbol": "ETH",
      "tokenDecimals": 18,
      "tokenType": "NATIVE",
      "holderAddress": "0xfa9019df60d3c710d7d583b2d69e18d412257617",
      "balance": "4.54492462147",
      "balanceRawInteger": "4544924621470000000",
      "balanceUsd": "0",
      "tokenPrice": "0",
      "thumbnail": "https://www.ankr.com/protocol/static/media/eth.3ee8ddd4.svg"
    }
...
]

```

**Expected result for ETH tokenPrice**
The current ETH price

**Comment by bogatyr285** [comment]
Greetings!

Thanks for feedback and providing details. 
We've fixed this issue. Please try again
