### ISSUE TITLE
ankr_getAccountBalance is not stable 

### ISSUE THREAD

**Issue by aminhdev** [Ankr-network/ankr.js#12]
**My problem**
I used "@ankr.com/ankr.js@0.1.12" package for get account balance with my premium plan, tried to call  ankr_getAccountBalance 10 times, 5 times I got empty returned result 

**This is my request params**
![Screenshot 2022-11-07 at 11 23 40](https://user-images.githubusercontent.com/22216884/200226848-cb3d537f-f694-421d-9607-31716bcbfbb2.png)

**Current result: 5 times got this empty result / total 10 tried requests**
![Screenshot 2022-11-07 at 11 24 33](https://user-images.githubusercontent.com/22216884/200226867-98e1e615-1c85-4f5c-9838-b5bf48258cb2.png)

**Expected**
With the same request above the method should return data instead of empty result in the randomly time
![image](https://user-images.githubusercontent.com/22216884/200227553-8b1a777e-c097-4667-9dad-81f9d2250504.png)

**Comment by bogatyr285** [comment]
```
curl --location --request POST 'https://rpc.ankr.com/multichain' \
--header 'Content-Type: application/json' \
--header 'X-API-KEY: $$$$$$$$$$$$$$$$$$$$$$' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "ankr_getAccountBalance",
    "params": {  
        "walletAddress": "0xb644e9b2b38da1752da7ae3767e829bcabbf688f",
        "pageSize": 10000
    },
    "id": 1
}'
```

Request works well even if call it multiple time. Please try again and you can remove `onlyWhitelisted` param(which can be buggy at current moment). 
Please text us about your results

**Comment by aminhdev** [comment]
Thanks for your info, let me try it

**Comment by aminhdev** [comment]
> ```
> curl --location --request POST 'https://rpc.ankr.com/multichain' \
> --header 'Content-Type: application/json' \
> --header 'X-API-KEY: $$$$$$$$$$$$$$$$$$$$$$' \
> --data-raw '{
>     "jsonrpc": "2.0",
>     "method": "ankr_getAccountBalance",
>     "params": {  
>         "walletAddress": "0xb644e9b2b38da1752da7ae3767e829bcabbf688f",
>         "pageSize": 10000
>     },
>     "id": 1
> }'
> ```
> 
> Request works well even if call it multiple time. Please try again and you can remove `onlyWhitelisted` param(which can be buggy at current moment). Please text us about your results

Its working as expected for now, thanks and closed this issue
