### ISSUE TITLE
how to connect to polygon mumbai testnet ?

### ISSUE THREAD

**Issue by tirajetw** [Ankr-network/ankr.js#14]

**Comment by romanankr** [comment]
We do not support testnets at the moment, but have it planned. ETA is by the end of the year.

**Comment by samepant** [comment]
@romanankr any update on testnet support? would love to be able to test ankr on goerly 🙏

**Comment by romanankr** [comment]
> @romanankr any update on testnet support? would love to be able to test ankr on goerly 🙏

Hey, I've just released the new `v0.3.1` version with `eth_goerli` and `avalanche_fuji` support enabled. We're also currently working on adding support to `polygon_mumbai` testnet, ETA is 1-2 weeks.

**Comment by samepant** [comment]
@romanankr thanks for making the update! any chance we could see this new version integrated into the `ankr-react` package? that's how i'm using ankr.js atm.

**Comment by romanankr** [comment]
> @romanankr thanks for making the update! any chance we could see this new version integrated into the `ankr-react` package? that's how i'm using ankr.js atm.

hey, unfortunately at the moment we don't have enough resources to keep it updated, but PRs are always welcome 🙂

**Comment by system32uwu** [comment]
@romanankr gm, does Ankr itself support Polygon Mumbai? Doesn't seem to be listed here: https://www.ankr.com/rpc/

**Comment by romanankr** [comment]
> @romanankr gm, does Ankr itself support Polygon Mumbai? Doesn't seem to be listed here: https://www.ankr.com/rpc/

It does, I believe if you open Polygon chain there's testnet option

**Comment by RedCuckoo** [comment]
Polygon Mumbai is currently supported in [v0.5.0](https://github.com/Ankr-network/ankr.js/releases/tag/v0.5.0)
