### ISSUE TITLE
The information retrieved through getNFTsByOwner is different

### ISSUE THREAD

**Issue by blockdev337** [Ankr-network/ankr.js#17]
The metadata information obtained through getNFTsByOwner does not match what is in opensea.

The json below is the NFT information obtained through ankr.

ANKR owner: 0xc8B1735929eDa28822721fd9Bdbb1D3de2b3eab2

{

                "contract": {

                    "address": "0x1f47ea34d27ecf77bf04a702fbd9e7b7a4b38024",

                    "name": "Merge Machines",

                    "symbol": "MERGE",

                    "totalSupply": "",

                    "tokenType": "ERC721"

                },

                "tokenId": "1128",

                "tokenType": "ERC721",

                "title": "Kinetic #1128",

                "description": "",

                "tokenUri": {

                    "raw": "https://mergemachines-data.uc.r.appspot.com/metadata/1128",

                    "gateway": "https://mergemachines-data.uc.r.appspot.com/metadata/1128"

                },

                "media": {

                    "raw": "https://storage.googleapis.com/merge-machines-images/gif/1128.gif",

                    "gatewal": "https://storage.googleapis.com/merge-machines-images/gif/1128.gif"

                },

                "balance": 1

            }

https://opensea.io/assets/ethereum/0x1f47ea34d27ecf77bf04a702fbd9e7b7a4b38024/1128

**Comment by RedCuckoo** [comment]
@blockdev337 Thank you for raising an issue here. As a solution, we are planning to provide the option for users, to force update data from the blockchain with the request. I will get back to you when this will be implemented.

**Comment by RedCuckoo** [comment]
The issue has been resolved, the requested data was updated.

A new feature: force update data from the blockchain with the request ankr_getNftMetadata is possible now by passing the _forceFetch_ parameter with a _true_ value. https://www.ankr.com/docs/advanced-api/specification/#tag/NFT-API/paths/~1?ankr_getNFTMetadata/post
