### ISSUE TITLE
Remove typescript from production dependencies?

### ISSUE THREAD

**Issue by mattcasey** [Ankr-network/ankr.js#29]
Hi, we are trying to get our production builds down. Typescript should probably just be a dev dependency, but right now it's tracked in 'dependencies' in ankr.js, so when we use this library and run `npm prune --omit=dev`, it does not get uninstalled.

**Comment by kfastov** [comment]
@mattcasey Thank you for your report, we've fixed it in the latest release (v0.4.2)
